import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchPostsDetail } from './postsStatusAPI';

const initialState = {
  value: 0,
  status: 'idle',
  data:  [],
  comments: [],
  limit: 0,
  page: 1,
  prevY: 0
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(getPostsAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getPostDetailAsync = createAsyncThunk(
  'status/fetchPostsDetail',
  async (page) => {
    const response = await fetchPostsDetail(page);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const postsDetailReducer = createSlice({
  name: 'status',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    incrementPage: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.page += 1;
    },
    changeY: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.prevY = action.payload;
    },
    decrementPage: (state) => {
      state.page -= 1;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getPostDetailAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getPostDetailAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.comments = action.payload?.comments;
      });
  },
});

export const { incrementPage, decrementPage, changeY } = postsDetailReducer.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.posts.value)`
export const comments = (state) => state.status.comments;

export default postsDetailReducer.reducer;
